### ISSUE TITLE
docker:push failed with ARG in FROM

### ISSUE THREAD

**Issue by ChristianKnof** [fabric8io/docker-maven-plugin#1778] opened 2024-04-12 09:40 UTC
### Description
As seen in the example [dockerfile-base-as-arg|https://github.com/fabric8io/docker-maven-plugin/blob/master/it/dockerfile-base-as-arg/src/main/docker/Dockerfile] we tried to parametrize our docker-builds, the docker:build works fine, but the following docker:push crashes with:

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.44.0:push (default-cli) on project xxx: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.44.0:push failed: Given Docker name '${baseImage}' is invalid:
[ERROR]    * image part '${baseImage}' doesn't match allowed pattern '[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?'

### Info
OUR: Property:
`<docker.buildArg.baseImage>privateImageRegistry/privateImage:CustomTag</docker.buildArg.baseImage>`

OUR-Configuration:
`			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<configuration>
					<images>
						<image>
							<name>${docker-registry.url}/${project.artifactId}:${project.version}</name>
							<build>
								<contextDir>${project.basedir}</contextDir>
								<dockerFile>${project.basedir}/docker/Dockerfile</dockerFile>
								<noCache>true</noCache>
							</build>
						</image>
					</images>
				</configuration>
			</plugin>`
OUR simplified Dockerfile:
`ARG baseImage
FROM ${baseImage}`

* docker-maven-plugin version : 0.44.0
* Maven version (`mvn -v`) : 3.9.4

**Comment by rohanKanojia** [comment] 2024-04-12 09:49
Do you think this is duplicate of https://github.com/fabric8io/docker-maven-plugin/issues/1756 ? Could you please check via [SNAPSHOT](https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/HowToUseDockerMavenPluginSnapshotArtifacts.md) build if it's working as expected?

**Comment by rohanKanojia** [comment] 2024-04-13 17:00
@ChristianKnof : Thanks for reporting! I can reproduce the issue.

**Comment by nodece** [comment] 2024-04-29 16:08
Any updates?

**Comment by rohanKanojia** [comment] 2024-04-29 16:37
@nodece : Let me provide a fix this week.

**Closed** 2024-07-14 13:27 UTC
