### ISSUE TITLE
0.14.1 Dynamic values not assigned to maven properties 

### ISSUE THREAD

**Issue by basven** [fabric8io/docker-maven-plugin#399] opened 2016-02-25 21:04 UTC
I tried to assign ports to a maven property which would fail. So I tried the sample provided but am getting the same error:

Failed to execute goal io.fabric8:docker-maven-plugin:0.14.1:start (start) on project docker-jolokia-demo: Execution start of goal io.fabric8:docker-maven-plugin:0.14.1:start failed: Illegal character in authority at index 7: http://${jolokia.host}:${jolokia.port}/jolokia 

I have tried both <port>${jolokia.port}:8080</port> and <port>jolokia.port:8080</port>

**Comment by rhuss** [comment] 2016-02-25 21:21
Could you tell the command you used ? I just tried it and it works [without problem](https://gist.github.com/561cf8e1195eb641c78f)

Could you gist the command you used and output of your run ?

**Comment by basven** [comment] 2016-02-26 23:08
Weird, I posted a long answer here yesterday but apparently that wasn't saved.  
I tried both 'mvn clean install' and 'mvn verify', both with the same result.

Output from mvn --version:

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T09:41:47-07:00)
Maven home: /home/bven/devel/maven
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /home/bven/devel/jdk1.8.0_45/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-37-generic", arch: "amd64", family: "unix"

The problem is in the 'wait' where I try to use the maven properties to connect to a known URL and those properties are not being 'converted' to their values but are instead the property names, so it is trying to connect to  http://${jolokia.host}:${jolokia.port}/jolokia instead of http://localhost:12345/whatever

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building docker-jolokia-demo 0.14.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> docker-maven-plugin:0.14.1:source (sources) > generate-sources @ docker-jolokia-demo >>>
[INFO] 
[INFO] <<< docker-maven-plugin:0.14.1:source (sources) < generate-sources @ docker-jolokia-demo <<<
[INFO] 
[INFO] --- docker-maven-plugin:0.14.1:source (sources) @ docker-jolokia-demo ---
[INFO] Reading assembly descriptor: /home/bven/devel/docker-maven-plugin-master/samples/data-jolokia-demo/src/main/docker/assembly.xml
[WARNING] Cannot include project artifact: io.fabric8:docker-jolokia-demo:jar:0.14.1; it doesn't have an associated file or directory.
[WARNING] Cannot include project artifact: io.fabric8:docker-jolokia-demo:jar:0.14.1; it doesn't have an associated file or directory.
[INFO] Copying files to /home/bven/devel/docker-maven-plugin-master/samples/data-jolokia-demo/target/docker/fabric8/docker-jolokia-demo/0.14.1/build/maven
[INFO] Building tar: /home/bven/devel/docker-maven-plugin-master/samples/data-jolokia-demo/target/docker/fabric8/docker-jolokia-demo/0.14.1/tmp/docker-build.tar
[INFO] DOCKER> [fabric8/docker-jolokia-demo:0.14.1] "data": Created docker source tar /home/bven/devel/docker-maven-plugin-master/samples/data-jolokia-demo/target/docker/fabric8/docker-jolokia-demo/0.14.1/tmp/docker-build.tar
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ docker-jolokia-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/bven/devel/docker-maven-plugin-master/samples/data-jolokia-demo/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ docker-jolokia-demo ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ docker-jolokia-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/bven/devel/docker-maven-plugin-master/samples/data-jolokia-demo/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ docker-jolokia-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ docker-jolokia-demo ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ docker-jolokia-demo ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] 
[INFO] --- docker-maven-plugin:0.14.1:build (start) @ docker-jolokia-demo ---
[INFO] Reading assembly descriptor: /home/bven/devel/docker-maven-plugin-master/samples/data-jolokia-demo/src/main/docker/assembly.xml
[INFO] Copying files to /home/bven/devel/docker-maven-plugin-master/samples/data-jolokia-demo/target/docker/fabric8/docker-jolokia-demo/0.14.1/build/maven
[INFO] Building tar: /home/bven/devel/docker-maven-plugin-master/samples/data-jolokia-demo/target/docker/fabric8/docker-jolokia-demo/0.14.1/tmp/docker-build.tar
[INFO] DOCKER> Step 1 : FROM busybox:latest
[INFO] DOCKER> ---> 65e4158d9625
[INFO] DOCKER> Step 2 : COPY maven /tmp/3e47a083-a00f-43b1-b553-fd3a9033341c/maven/
[INFO] DOCKER> ---> 7d1fae0fdcbd
[INFO] DOCKER> Removing intermediate container 3876fa54525e
[INFO] DOCKER> Step 3 : USER root
[INFO] DOCKER> ---> Running in 167b27dede95
[INFO] DOCKER> ---> 68e20717eb82
[INFO] DOCKER> Removing intermediate container 167b27dede95
[INFO] DOCKER> Step 4 : RUN chown -R www-data:www-data /tmp/3e47a083-a00f-43b1-b553-fd3a9033341c && cp -rp /tmp/3e47a083-a00f-43b1-b553-fd3a9033341c/* / && rm -rf /tmp/3e47a083-a00f-43b1-b553-fd3a9033341c
[INFO] DOCKER> ---> Running in e7c9476d55c0
[INFO] DOCKER> ---> 5da295a7218a
[INFO] DOCKER> Removing intermediate container e7c9476d55c0
[INFO] DOCKER> Step 5 : USER www-data
[INFO] DOCKER> ---> Running in c4d999bb85cd
[INFO] DOCKER> ---> 41ceffd3c073
[INFO] DOCKER> Removing intermediate container c4d999bb85cd
[INFO] DOCKER> Step 6 : VOLUME /maven
[INFO] DOCKER> ---> Running in 7bd9460183ee
[INFO] DOCKER> ---> 3477f6fa4107
[INFO] DOCKER> Removing intermediate container 7bd9460183ee
[INFO] DOCKER> Successfully built 3477f6fa4107
[INFO] DOCKER> [fabric8/docker-jolokia-demo:0.14.1] "data": Built image 3477f6fa4107
[INFO] DOCKER> [fabric8/docker-jolokia-demo:0.14.1] "data": Removed image 209193e25bf7
[INFO] DOCKER> [fabric8/docker-jolokia-demo:0.14.1] "data": Tag with latest
[INFO] 
[INFO] --- docker-maven-plugin:0.14.1:start (start) @ docker-jolokia-demo ---
[INFO] DOCKER> [fabric8/docker-jolokia-demo:0.14.1] "data": Start container 9feae1b1f955
[INFO] DOCKER> ... latest Pulling from consol/tomcat-7.0
[INFO] DOCKER> ... Digest: sha256:8256b5e8e01fc4f6c1913e1fd70dea95ae656400f70fb1c12157d0e89e1ccaf7
[INFO] DOCKER> ... Status: Image is up to date for consol/tomcat-7.0:latest
[INFO] DOCKER> [consol/tomcat-7.0:latest] "server": Start container 910f13b0c778
16:07:18.128 server> Checking *.war in /maven
16:07:18.129 server> Linking /maven/jolokia-it.war --> /opt/tomcat/webapps/jolokia-it.war
16:07:18.132 server> Linking /maven/jolokia.war --> /opt/tomcat/webapps/jolokia.war
[ERROR] DOCKER> Error occurred during container startup, shutting down...
[INFO] DOCKER> [consol/tomcat-7.0:latest] "server": Stop and remove container 910f13b0c778
[INFO] DOCKER> [fabric8/docker-jolokia-demo:0.14.1] "data": Stop and remove container 9feae1b1f955
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.923 s
[INFO] Finished at: 2016-02-26T16:07:19-07:00
[INFO] Final Memory: 22M/279M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.14.1:start (start) on project docker-jolokia-demo: Execution start of goal io.fabric8:docker-maven-plugin:0.14.1:start failed: Illegal character in authority at index 7: http://${jolokia.host}:${jolokia.port}/jolokia -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by rhuss** [comment] 2016-02-27 11:02
Could you please tell me also what version of Docker you are using and what's you Docker setup (docker daemong running locally, or within a VM like with docker-machine or boot2docker ....) ?

thanks ...

**Comment by rhuss** [comment] 2016-02-27 12:21
If you change within the pom.xml the version of the maven plugin to 0.13.9 (and the group id to `org.jolokia`) does it work then ?

**Comment by basven** [comment] 2016-02-29 16:23
docker --version
Docker version 1.9.1, build a34a1d5

I run in 'host' mode on Ubuntu, in bridge mode on a MAC (talking to a VM).
I noticed some other anomalies:
On the MAC I can never communicate to port 4447 (I am running jboss inside the docker image and that port is used to remotely call into EJBs).  On the Ubuntu machine that happened once.
On the Ubuntu machine it talked to that port although I forgot to open it in my image configuration.
When I do a docker ps, no ports are showing at all.
When I tried to add the <portPropertyFile> tag, no file was generated.

I would like to try out version 0.13.9, but it doesn't support the <net> tag, what is the equivalent for that when running in 'host' mode?

**Comment by rhuss** [comment] 2016-02-29 16:33
wdym with 'host' mode ? I am assuming that you are running the provided demo unchanged ? If you changed, could you please post the changes you did so that I could reproduce it ?

**Comment by basven** [comment] 2016-02-29 16:43
I made no changes to the demo, those remarks were based on my application and pom definition.
In 0.14.1 I have this in my pom:
<net>host</net>
How do I tell in 0.13.9 to do the same? 
I couldn't find the source for 0.13.9 so tried using my definitions.

**Comment by basven** [comment] 2016-02-29 16:43
I meant: <net>host</net>

**Comment by basven** [comment] 2016-02-29 16:44
crap, ok &lt net $gt, hope you are getting it,`<net>host</net>`

**Comment by rhuss** [comment] 2016-02-29 16:52
;-) np (when using xml you better escape it with ``, I fixed your comment above)

`<net>host</net>` is new in 0.14.1, indeed. 

In fact, if you use `host` as networking mode, not port mapping happens at all and the declaration is ignored. The image bounds its ports to exactly the same port as configured on the Docker host itself (it share the same networkspace as the docker host). Since you already know the port (which is `8080` in this example) you could use it directly.

I will prepare a dedicated profile in the example, which shows the usage with `<net>host</net>`

**Comment by basven** [comment] 2016-02-29 17:00
That makes sense and explains why it worked when i didn't configure the ports explicitly.  I need the ability to run integration tests in both host and bridge mode (we have a diversity of developers here, most on windows) so from a consistency point of view it would be nice to just always map to variables if specified.  

Any idea on why, in bridge mode, one port (8080) responds ( my wait URL gets a response) but another port (4447) doesn't (although netstat shows it is open) or on how to trouble-shoot that ?

**Comment by rhuss** [comment] 2016-02-29 17:09
@basven you can prepopulate the variable in the host mode variant e.g. by using a dedicated profile or `-Djolokia.port=8080`. The mapping will fill in the variable only when not already set (but at the end for "host" mode its ignored completely). But you are probably right, in host mode it would make sense to simply copy over the port into an empty variable.

for your issue, I have probably no solution for you out of the box (of course it depends what behind that port 4447). Remember, if you are in "host" mode on you linux machine it will bind to the host and port directly, so you don't need to expose any port of course. When you application binds to 4447 you should take care on which interface it binds, too (best would be binding on every interface).

If you don't mind I'd like to close the issue and open a new one for the "portmapping copy". Feel free to reopen if you think there's an issue with this plugin.

**Closed by rhuss** 2016-02-29 17:09 UTC

**Comment by basven** [comment] 2016-02-29 17:42
thanks for the help; I will try to trouble-shoot the bridge port issue. (jboss is the application behind it).
