### ISSUE TITLE
Arg properties not work

### ISSUE THREAD

**Issue by SirWayne** [fabric8io/docker-maven-plugin#1110] opened 2018-10-10 09:19 UTC
Hello

i try to set a docker ARG over property, which is not work

DockerFile:
```
ARG NANO_SERVER_DOCKER_TAG=10.0.14393.1770
FROM microsoft/windowsservercore:$NANO_SERVER_DOCKER_TAG as builder
```

pom.xml

```
<properties> 
 <docker.buildArg.NANO_SERVER_DOCKER_TAG>10.0.14393.1770</docker.buildArg.NANO_SERVER_DOCKER_TAG>
</properties>
```

Error

`**Unable to check image [microsoft/windowsservercore:$NANO_SERVER_DOCKER_TAG]**`

So the ARG has not been replaced

### Info

* d-m-p version : 0.27.2

**Comment by rhuss** [comment] 2018-10-10 17:33
Can you use this Dockerfile outside of d-m-p ? (i.e with plain Docker ?). I'm asking as build args for FROM has been introduced just in of the newer Docker version and your Docker daemon might be too old.

**Comment by SirWayne** [comment] 2018-10-11 12:06
Yes this works, iam using the newest docker version.

**Comment by PieterJanVanAeken** [comment] 2019-02-12 16:40
I think this might be a duplicate of this. Build args in the from clause do not seem to be interpreted atm.

https://github.com/fabric8io/docker-maven-plugin/issues/859

**Comment by edrandall** [comment] 2019-03-02 10:09
args set in my pom f-m-p plugin configuration section seem to have no effect.
Using f-m-p 3.5.42 with mode=openshift and an external Dockerfile  
` <configuration> <images> <image> <build><dockerFileDir>. `
Found that any args set in the `<configuration>` have no effect.  Forced to use values under global <properties> only.

**Comment by rhuss** [comment] 2019-04-06 18:59
@edrandall Do you have a concrete example for what you used ? I.e. a full pom.xml configuration would be very helpful.

**Comment by rhuss** [comment] 2019-04-06 18:59
Closing this as a duplicate of #859

**Closed by rhuss** 2019-04-06 18:59 UTC
