### ISSUE TITLE
Container can't see each other when running through plugin

### ISSUE THREAD

**Issue by Fluxxo** [fabric8io/docker-maven-plugin#715] opened 2017-02-16 08:31 UTC
Hi there, me again.

At first: I really love the concept of this plugin. The spotify plugin dies its job, still this one is the solution to a lot of my problems.

I put together a little test case because I ran into a problem setting up my integration tests.

Wheny you run the verify phase, this happens:

* Download the mysql image & run it
* Download the openjdk8 image, build the new image and run it as well

The entrypoint is configured to execute a java class that simply should connect to mysql. 

When the containers are run by the plugin, the simple class trying to connect to mysql can't connect:

```
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:590)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:57)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.fluxxo.docker.TestJdbc.main(TestJdbc.java:16)
Caused by: com.mysql.cj.core.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:93)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:133)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:149)
	at com.mysql.cj.mysqla.io.MysqlaSocketConnection.connect(MysqlaSocketConnection.java:83)
	at com.mysql.cj.mysqla.MysqlaSession.connect(MysqlaSession.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1726)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1596)
	... 6 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.cj.core.io.StandardSocketFactory.connect(StandardSocketFactory.java:202)
	at com.mysql.cj.mysqla.io.MysqlaSocketConnection.connect(MysqlaSocketConnection.java:57)
	... 9 more
```

Because auf the configuration and a nice Thread.sleep() The container (connectiontest) remains alive. When entering the container with docker exec -it $containerid bash I can issue a ping mysql and I get a response. So networking seems to work.

If I run that container like "docker run (-it OR -d) --link $mysqlcontainername:mysql connectiontest" it works as well.

So, the scenario is:

Everything works as expected: 

- The testconatienr can ping mysql 
- Running and linking the containers manually works as well

As soon as the containers get started by the plugin, the process can't connect. I don't have a clue if they can't see each other, but at least the connection to the required port does not work work out correctly.

The test case is here: https://github.com/Fluxxo/dmp-test

Any idea what's going wrong and how to trace it down?

**Comment by rhuss** [comment] 2017-02-16 09:11
In short, the problem is the wait on the mysql output, which appears twice, and only after the last one the db is ready. I send you a PR to https://github.com/Fluxxo/dmp-test/pull/1 explaining it in more detail.

**Comment by Fluxxo** [comment] 2017-02-16 09:59
Hey,

just when you wrote I found it out as well. I was trying to telnet on the port and saw that there must have been a timing issue and then saw the two identical strings.

MySQL prints out the relevant string for each port (socket, 3306) it bootstraps.

Thanks for you fast response, that was a nasty one, but actually you found it out pretty fast :)

Thanks!!

**Comment by rhuss** [comment] 2017-02-16 10:07
you are welcome. I'll close this issue if you don't mind, feel free to reopen it in case.

**Closed by rhuss** 2017-02-16 10:07 UTC
Labels: question
