### ISSUE TITLE
buildx cache-from / cache-to

### ISSUE THREAD

**Issue by owetterau** [fabric8io/docker-maven-plugin#1621] opened 2022-11-25 13:42 UTC
Hello,

I am wondering how to set 'cache-from' and 'cache-to' when using buildx to build multi-platform images.

I have a maven project in which several Docker images are being built and some of them depend on each other. Unfortunately, when a depending Docker image is being built, Docker tries to download the base Docker image (as defined by 'FROM' in the Dockerfile) instead of reusing the already built one. This obviously fails.

I have already tested if using 'dockerStateDir' helps, but it did not work either.

Because of this I would like to use the 'cache-from' and 'cache-to' option of buildx but do not know how to do this with the docker-maven-plugin (and if it is possible at all).

Does anybody have an idea how to solve this issue?

### Info

* docker-maven-plugin version : 0.40.2
* Maven version (`mvn -v`) : 3.8.1
* Docker version : 20.10.21

**Comment by rhuss** [comment] 2023-02-14 11:21
I'm not directly connected to the buildx implementation, but it sounds like a useful addition. @chonton maybe something that could be considered in the future ? Would this make sense ?

**Comment by chonton** [comment] 2023-02-14 16:29
Maybe. The problem is that you get one export location per build - either the local filesystem or the registry.  If we build the base image into the local filesystem, we can then build the dependent image and push that into registry.  However, the base image will not be available in the registry.  So you have to introduce another build that basically is a FROM base image and pushes to registry.

I wonder if a multi-stage build might work out.  If the base stages are identical in the two dependents, then buildx is smart enough to use the cached layers.  It is a build, but it is a fast build.

I also wonder if the problem is a side effect of how the build/push mojos are working.  The build mojo builds the native image into the cache, not into the registry.  The push mojo builds both native platform (fast build due to cache) and non-native platforms and pushes all platforms to the registry.

@owetterau Please comment on the docker cli commands you think would work for your use case.

**Comment by rohanKanojia** [comment] 2023-11-29 05:03
@orange-buffalo : Do you think #1717 is related to this issue?

**Comment by orange-buffalo** [comment] 2023-11-29 05:17
Yes, this PR is related. It provides existing configuration option into buildX `--no-cache` arg. My suggestion is to implement similar functionality for `--cache-from` and `--cache-to` args, adding new config to the plugin.

To me it sounds logical to include this configuration into `buildX` of `image.build`:
```xml
<configuration>
  <images>
    <image>
      <name>my-registry/my-image:${project.version}</name>
      <build>
        <buildx>
          <!-- already supported properties -->
          <builderName>my_name</builderName>
          <platforms>
            <platform>linux/amd64,linux/arm64</platform>
          </platforms>
          <!-- new properties -->
          <cacheFrom>my-registry/my-image-cache:latest</cacheFrom>
          <cacheTo>my-registry/my-image-cache:latest</cacheTo>
        </buildx>
```
And also add support to override them with system properties, like in the referenced PR:
https://github.com/fabric8io/docker-maven-plugin/blob/1b4dec5b5eda5cc3255fb225269cc46256dd40e9/src/main/java/io/fabric8/maven/docker/config/ConfigHelper.java#L176-L180

**Comment by rohanKanojia** [comment] 2023-11-29 06:25
@owetterau : Sounds good to me, Shall I assign this issue to you?

**Comment by orange-buffalo** [comment] 2023-11-29 06:28
Sure, let's do that. I expect to provide a PR during the next week or two.

**Comment by rohanKanojia** [comment] 2023-11-29 06:36
@orange-buffalo : Thanks a lot!

**Closed** 2023-12-03 15:55 UTC

**Comment by ggjulio** [comment] 2024-09-20 07:52
Having two `cacheFrom` is a common pattern but currently not supported by the plugin.
I opened an issue #1822
