### ISSUE TITLE
Build of Dockerfile with multistage build fails on private registry

### ISSUE THREAD

**Issue by AlesRybak** [fabric8io/docker-maven-plugin#1142] opened 2018-12-17 17:58 UTC
### Description

We have private docker registry which requires authenication (we tried to pass the user and password via `.m2/settings.xml`, directly via CLI params and by logging in via docker, it's all the same
). The build fails when Dockerfile contains multi-staged build (Dockerfile contains multiple FROM statements), specifically on the second FROM statement with 
```Unable to build image [docker-develop.lnd.bz/sandbox/dmpmsbp:latest] : "Get https://docker.lnd.bz/v2/nginx/manifests/1.10: no basic auth credentials"```

### Info

* **d-m-p version** : `0.21.0`, `0.28.0` (tested on both in hope that upgrade will help)
* **Maven version** (`mvn -v`) :
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
Default locale: en_CZ, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.2", arch: "x86_64", family: "mac"
```
* **Docker version** :
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
* **If it's a bug, how to reproduce** :
Sample pom.xml and Dockerfile attached. One would need private repo with authentication and docker images used in the Dockerfile not present on local system (so the download must occure). The first image is downloaded properly, the second one fails.

* **Sample project** : 
[dmpmsbp.zip](https://github.com/fabric8io/docker-maven-plugin/files/2687268/dmpmsbp.zip)
[maven-output.log](https://github.com/fabric8io/docker-maven-plugin/files/2687267/maven-output.log)

**Comment by xfh** [comment] 2019-10-17 17:32
I have the same problem with the latest version 0.31.0. I have a Dockerfile with `FROM XX as base`.

With imagePullPolicy IfNotPresent or Always:

> DOCKER> Unable to pull 'base:latest' : {"message":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"} (Not Found: 404) [{"message":"pull access denied for base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"} (Not Found: 404)]

With imagePullPolicy Never:
> DOCKER> No image 'base' found and pull policy 'Never' is set. Please chose another pull policy or pull the image yourself)

There is another duplicate here: #1264

**Comment by rhuss** [comment] 2019-10-18 07:11
thanks guys for the bug report !

@rohanKanojia is this something you could look into ? I'm not sure exactly how to hook in authentication for a multistage build.

btw, I believe multi-stage builds are a bit of an edge use case for d-m-p as dmp is supposed to drive the build, not the Dockerfile build-stage.

**Comment by rohanKanojia** [comment] 2019-10-21 12:53
Unfortunately, I could not reproduce this issue on latest version. I could reproduce it with 0.28.0(which is version used in the reproducer project given) but not with 0.31.0. i uploaded all the images to quay.io. I modified the dockerfile like this:
```
FROM quay.io/rohankanojia/debian:strech-slim as BUILD

RUN ls -la /

FROM quay.io/rohankanojia/nginx:latest

RUN ls -la /
```

And then I noticed that this is not reproducible on 0.31.0

- **Behavior with 0.28.0**
```
~/Downloads/dmpmsbp/dmpmsbp : $ mvn clean install
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< eu.lundegaard.sandbox:dmpmsbp >--------------------
[INFO] Building Docker Maven Plugin Multi-stage Build Problem 0.1.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dmpmsbp ---
[INFO] Deleting /home/rohaan/Downloads/dmpmsbp/dmpmsbp/target
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ dmpmsbp ---
[INFO] Installing /home/rohaan/Downloads/dmpmsbp/dmpmsbp/pom.xml to /home/rohaan/.m2/repository/eu/lundegaard/sandbox/dmpmsbp/0.1.0-SNAPSHOT/dmpmsbp-0.1.0-SNAPSHOT.pom
[INFO] 
[INFO] --- docker-maven-plugin:0.28.0:build (docker-build) @ dmpmsbp ---
[INFO] DOCKER> Pulling from rohankanojia/debian
80369df48736: Downloading [>                                                  ]  228.1kB/22.52MB
80369df48736: Downloading [=====>                                             ]  2.522MB/22.52MB
80369df48736: Downloading [==============>                                    ]  6.651MB/22.52MB
80369df48736: Downloading [========================>                          ]  11.24MB/22.52MB
80369df48736: Downloading [====================================>              ]  16.28MB/22.52MB
80369df48736: Downloading [=============================================>     ]  20.64MB/22.52MB
80369df48736: Verifying Checksum 
80369df48736: Download complete 
80369df48736: Extracting  [>                                                  ]  229.4kB/22.52MB
80369df48736: Extracting  [==========>                                        ]  4.588MB/22.52MB
80369df48736: Extracting  [============================>                      ]  12.62MB/22.52MB
80369df48736: Extracting  [===========================================>       ]   19.5MB/22.52MB
80369df48736: Extracting  [===============================================>   ]  21.56MB/22.52MB
80369df48736: Extracting  [==================================================>]  22.52MB/22.52MB
80369df48736: Pull complete 

[INFO] DOCKER> Digest: sha256:ed1b1afa74d1ea3c7ec2cb401fe02c9828b42522de433763d2fd492da22478f4
[INFO] DOCKER> Status: Downloaded newer image for quay.io/rohankanojia/debian:strech-slim
[INFO] DOCKER> Pulled quay.io/rohankanojia/debian:strech-slim in 5 seconds 
[INFO] Copying files to /home/rohaan/Downloads/dmpmsbp/dmpmsbp/target/docker/docker-develop.lnd.bz/sandbox/dmpmsbp/latest/build/maven
[WARNING] DOCKER> Dockerfile /home/rohaan/Downloads/dmpmsbp/dmpmsbp/Dockerfile does not contain an ADD or COPY directive to include assembly created at maven. Ignoring assembly.
[INFO] Building tar: /home/rohaan/Downloads/dmpmsbp/dmpmsbp/target/docker/docker-develop.lnd.bz/sandbox/dmpmsbp/latest/tmp/docker-build.tar
[INFO] DOCKER> [docker-develop.lnd.bz/sandbox/dmpmsbp:latest]: Created docker-build.tar in 84 milliseconds
[INFO] DOCKER> Step 1/4 : FROM quay.io/rohankanojia/debian:strech-slim as BUILD
[INFO] DOCKER> 
[INFO] DOCKER> ---> c2f145c34384
[INFO] DOCKER> Step 2/4 : RUN ls -la /
[INFO] DOCKER> 
[INFO] DOCKER> ---> Running in d3b18a27112e
[INFO] DOCKER> total 76
drwxr-xr-x.   1 root root 4096 Oct 21 12:49 .
drwxr-xr-x.   1 root root 4096 Oct 21 12:49 ..
-rwxr-xr-x.   1 root root    0 Oct 21 12:49 .dockerenv
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 bin
drwxr-xr-x.   2 root root 4096 Sep  8 10:51 boot
drwxr-xr-x.   5 root root  340 Oct 21 12:49 dev
drwxr-xr-x.   1 root root 4096 Oct 21 12:49 etc
drwxr-xr-x.   2 root root 4096 Sep  8 10:51 home
drwxr-xr-x.   8 root root 4096 Oct 14 00:00 lib
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 lib64
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 media
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 mnt
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 opt
dr-xr-xr-x. 278 root root    0 Oct 21 12:49 proc
drwx------.   2 root root 4096 Oct 14 00:00 root
drwxr-xr-x.   3 root root 4096 Oct 14 00:00 run
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 sbin
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 srv
dr-xr-xr-x.  13 root root    0 Oct 21 09:21 sys
drwxrwxrwt.   2 root root 4096 Oct 14 00:00 tmp
drwxr-xr-x.  10 root root 4096 Oct 14 00:00 usr
drwxr-xr-x.  11 root root 4096 Oct 14 00:00 var
[INFO] DOCKER> Removing intermediate container d3b18a27112e
[INFO] DOCKER> ---> b3e18eb4d1b7
[INFO] DOCKER> Step 3/4 : FROM quay.io/rohankanojia/nginx:latest
[INFO] DOCKER> 
[ERROR] DOCKER> Unable to build image [docker-develop.lnd.bz/sandbox/dmpmsbp:latest] : "unauthorized: access to the requested resource is not authorized"  ["unauthorized: access to the requested resource is not authorized" ]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.347 s
[INFO] Finished at: 2019-10-21T18:19:40+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.28.0:build (docker-build) on project dmpmsbp: Unable to build image [docker-develop.lnd.bz/sandbox/dmpmsbp:latest] : "unauthorized: access to the requested resource is not authorized"  -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

- **Behavior with 0.31.0**
```
~/Downloads/dmpmsbp/dmpmsbp : $ mvn clean install
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< eu.lundegaard.sandbox:dmpmsbp >--------------------
[INFO] Building Docker Maven Plugin Multi-stage Build Problem 0.1.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dmpmsbp ---
[INFO] Deleting /home/rohaan/Downloads/dmpmsbp/dmpmsbp/target
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ dmpmsbp ---
[INFO] Installing /home/rohaan/Downloads/dmpmsbp/dmpmsbp/pom.xml to /home/rohaan/.m2/repository/eu/lundegaard/sandbox/dmpmsbp/0.1.0-SNAPSHOT/dmpmsbp-0.1.0-SNAPSHOT.pom
[INFO] 
[INFO] --- docker-maven-plugin:0.31.0:build (docker-build) @ dmpmsbp ---
[INFO] DOCKER> Pulling from rohankanojia/debian
80369df48736: Downloading [>                                                  ]  229.4kB/22.52MB
80369df48736: Downloading [======>                                            ]  2.753MB/22.52MB
80369df48736: Downloading [==================>                                ]  8.258MB/22.52MB
80369df48736: Downloading [=============================>                     ]   13.3MB/22.52MB
80369df48736: Downloading [===============================================>   ]  21.58MB/22.52MB
80369df48736: Verifying Checksum 
80369df48736: Download complete 
80369df48736: Extracting  [>                                                  ]  229.4kB/22.52MB
80369df48736: Extracting  [=========>                                         ]  4.129MB/22.52MB
80369df48736: Extracting  [==========================>                        ]  12.16MB/22.52MB
80369df48736: Extracting  [==========================================>        ]  19.04MB/22.52MB
80369df48736: Extracting  [===============================================>   ]  21.56MB/22.52MB
80369df48736: Extracting  [==================================================>]  22.52MB/22.52MB
80369df48736: Pull complete 

[INFO] DOCKER> Digest: sha256:ed1b1afa74d1ea3c7ec2cb401fe02c9828b42522de433763d2fd492da22478f4
[INFO] DOCKER> Status: Downloaded newer image for quay.io/rohankanojia/debian:strech-slim
[INFO] DOCKER> Pulled quay.io/rohankanojia/debian:strech-slim in 5 seconds 
[INFO] DOCKER> Pulling from rohankanojia/nginx
ef24d3d19d38: Pull complete 
96ebebd48bf5: Pull complete 
783c67390305: Pull complete 
[INFO] DOCKER> Digest: sha256:0551bed9e1384d4de00e1bc0a5f08de991ec24736b62941dd2daf53aaf43e2ac
[INFO] DOCKER> Status: Downloaded newer image for quay.io/rohankanojia/nginx:latest
[INFO] DOCKER> Pulled quay.io/rohankanojia/nginx:latest in 7 seconds 
[INFO] Copying files to /home/rohaan/Downloads/dmpmsbp/dmpmsbp/target/docker/docker-develop.lnd.bz/sandbox/dmpmsbp/latest/build/maven
[WARNING] DOCKER> Dockerfile /home/rohaan/Downloads/dmpmsbp/dmpmsbp/Dockerfile does not contain an ADD or COPY directive to include assembly created at maven. Ignoring assembly.
[INFO] Building tar: /home/rohaan/Downloads/dmpmsbp/dmpmsbp/target/docker/docker-develop.lnd.bz/sandbox/dmpmsbp/latest/tmp/docker-build.tar
[INFO] DOCKER> [docker-develop.lnd.bz/sandbox/dmpmsbp:latest]: Created docker-build.tar in 131 milliseconds
[INFO] DOCKER> Step 1/4 : FROM quay.io/rohankanojia/debian:strech-slim as BUILD
[INFO] DOCKER> 
[INFO] DOCKER> ---> c2f145c34384
[INFO] DOCKER> Step 2/4 : RUN ls -la /
[INFO] DOCKER> 
[INFO] DOCKER> ---> Running in 9fc7e2b59a83
[INFO] DOCKER> total 76
drwxr-xr-x.   1 root root 4096 Oct 21 12:50 .
drwxr-xr-x.   1 root root 4096 Oct 21 12:50 ..
-rwxr-xr-x.   1 root root    0 Oct 21 12:50 .dockerenv
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 bin
drwxr-xr-x.   2 root root 4096 Sep  8 10:51 boot
drwxr-xr-x.   5 root root  340 Oct 21 12:50 dev
drwxr-xr-x.   1 root root 4096 Oct 21 12:50 etc
drwxr-xr-x.   2 root root 4096 Sep  8 10:51 home
drwxr-xr-x.   8 root root 4096 Oct 14 00:00 lib
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 lib64
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 media
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 mnt
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 opt
dr-xr-xr-x. 277 root root    0 Oct 21 12:50 proc
drwx------.   2 root root 4096 Oct 14 00:00 root
drwxr-xr-x.   3 root root 4096 Oct 14 00:00 run
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 sbin
drwxr-xr-x.   2 root root 4096 Oct 14 00:00 srv
dr-xr-xr-x.  13 root root    0 Oct 21 09:21 sys
drwxrwxrwt.   2 root root 4096 Oct 14 00:00 tmp
drwxr-xr-x.  10 root root 4096 Oct 14 00:00 usr
drwxr-xr-x.  11 root root 4096 Oct 14 00:00 var
[INFO] DOCKER> Removing intermediate container 9fc7e2b59a83
[INFO] DOCKER> ---> 3d3b26541362
[INFO] DOCKER> Step 3/4 : FROM quay.io/rohankanojia/nginx:latest
[INFO] DOCKER> 
[INFO] DOCKER> ---> 0346349a1a64
[INFO] DOCKER> Step 4/4 : RUN ls -la /
[INFO] DOCKER> 
[INFO] DOCKER> ---> Running in 23a286e9c5ea
[INFO] DOCKER> total 76
drwxr-xr-x.   1 root root 4096 Oct 21 12:50 .
drwxr-xr-x.   1 root root 4096 Oct 21 12:50 ..
-rwxr-xr-x.   1 root root    0 Oct 21 12:50 .dockerenv
drwxr-xr-x.   2 root root 4096 Mar 20  2017 bin
drwxr-xr-x.   2 root root 4096 Dec 28  2016 boot
drwxr-xr-x.   5 root root  340 Oct 21 12:50 dev
drwxr-xr-x.   1 root root 4096 Oct 21 12:50 etc
drwxr-xr-x.   2 root root 4096 Dec 28  2016 home
drwxr-xr-x.   1 root root 4096 Mar 27  2017 lib
drwxr-xr-x.   2 root root 4096 Mar 20  2017 lib64
drwxr-xr-x.   2 root root 4096 Mar 20  2017 media
drwxr-xr-x.   2 root root 4096 Mar 20  2017 mnt
drwxr-xr-x.   2 root root 4096 Mar 20  2017 opt
dr-xr-xr-x. 278 root root    0 Oct 21 12:50 proc
drwx------.   2 root root 4096 Mar 20  2017 root
drwxr-xr-x.   3 root root 4096 Mar 20  2017 run
drwxr-xr-x.   2 root root 4096 Mar 20  2017 sbin
drwxr-xr-x.   2 root root 4096 Mar 20  2017 srv
dr-xr-xr-x.  13 root root    0 Oct 21 09:21 sys
drwxrwxrwt.   1 root root 4096 Mar 27  2017 tmp
drwxr-xr-x.   1 root root 4096 Mar 27  2017 usr
drwxr-xr-x.   1 root root 4096 Mar 27  2017 var
[INFO] DOCKER> Removing intermediate container 23a286e9c5ea
[INFO] DOCKER> ---> bb1f5b6a230c
[INFO] DOCKER> Successfully built bb1f5b6a230c
[INFO] DOCKER> Successfully tagged docker-develop.lnd.bz/sandbox/dmpmsbp:latest
[INFO] DOCKER> [docker-develop.lnd.bz/sandbox/dmpmsbp:latest]: Built image sha256:bb1f5
[INFO] DOCKER> [docker-develop.lnd.bz/sandbox/dmpmsbp:latest]: Tag with latest
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.402 s
[INFO] Finished at: 2019-10-21T18:21:00+05:30
[INFO] ------------------------------------------------------------------------
~/Downloads/dmpmsbp/dmpmsbp : $ 
```

- **My docker version**:
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:46 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:51:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

@AlesRybak  @xfh : Could you guys please check if I missed something here? I have tested this 2-3 times but could not reproduce it either on master or on 0.31.0

**Comment by AlesRybak** [comment] 2019-10-21 13:19
Hi @rohanKanojia, I was unable to reproduce it on 0.31.0 as well, it worked fine for me. I would consider this fixed, thank you.

**Comment by rohanKanojia** [comment] 2019-10-21 13:37
@AlesRybak : oh, I see. Thanks for taking time to reproduce this! Shall we close this then?

**Comment by xfh** [comment] 2019-10-21 13:41
Wait a second: you missed a use case :-)

I use a Dockerfile that has a target to create an image for a (local) development environment, and a final one for deployment:

```
FROM quay.io/rohankanojia/debian:strech-slim as BUILD

RUN ls -la /

FROM BASE as DEVELOPMENT

RUN ls -la /

FROM BASE AS DEPOYLABLE

RUN ls -la /
```

**Comment by xfh** [comment] 2019-10-21 13:43
I guess you could close this issue, since my use case is probably better described by #1264

**Comment by rohanKanojia** [comment] 2019-10-21 13:46
@xfh: oh, okay. I would close this and investigate #1264 then ;-)

**Closed by rohanKanojia** 2019-10-21 13:46 UTC

**Comment by xfh** [comment] 2019-10-21 13:47
Thanks, I just confirmed as well, that multistage with FROM statements referring to registry-images like in your example above works.
