### ISSUE TITLE
Cannot temporarily tag because target image already exists

### ISSUE THREAD

**Issue by NancyChunlan** [fabric8io/docker-maven-plugin#838] opened 2017-08-14 08:55 UTC
Sometimes when we have target image already existing in system, and so caused the docker-maven-plugin failed to temporarily tag. After checked, found following code.       
```
 if (!name.hasRegistry() && registry != null) {
            if (hasImage(targetImage)) {
                throw new DockerAccessException(
                    String.format("Cannot temporarily tag %s with %s because target image already exists. " +
                                  "Please remove this and retry.",
                                  name.getFullName(), targetImage));
            }
```
I guess it's abnormal to interrupt the docker push with such errors, is it possible to remove the exception or add a parameter to toggle on/off the exception?

**Comment by ayen-tibco** [comment] 2017-11-27 16:06
Please remove this codeline as the user's docker version tag will take care of replacing it OR failing to let the user know of an existing tag image.

[https://stackoverflow.com/questions/31605661/how-to-prevent-docker-images-on-docker-hub-from-being-overwritten](url)

**Comment by adam66** [comment] 2017-12-06 17:13
Just hit this problem after changing my config from 

                <configuration>
                    <images>
                        <image>
                            <name>my-registry:12345/my-app</name>
                            <build>
                                <tags>
                                    <tag>latest</tag>

to 

                <configuration>
                    <pushRegistry>my-registry:12345</pushRegistry>
                    <images>
                        <image>
                            <name>my-app</name>
                            <build>
                                <tags>
                                    <tag>latest</tag>

**Comment by gnboorse** [comment] 2018-02-20 18:23
I am having this issue as well on several projects, but not on others.

Is there any update to the status of the code that @NancyChunlan pasted above?

**Comment by NancyChunlan** [comment] 2018-06-07 10:50
@gnboorse  I didn't get any update yet, as workaround, we use script to remove target images before the plugin.

**Comment by gnboorse** [comment] 2018-06-07 12:32
@NancyChunlan we ended up moving away from this plugin actually. We are now doing the docker and java builds separately.

**Comment by rhuss** [comment] 2018-06-13 09:33
Sorry for the super late response, not sure why this issue was below my radar.

I agree that we should be more conservative here and I'm going to tackle this for the next release.

**Comment by michaelze** [comment] 2019-01-04 08:54
@rhuss 
Any update on this? I'm running into the same issue and there have been two releases since your last post as far as I can tell.

**Comment by jroper** [comment] 2019-03-05 04:54
Fixed in #1170.

**Closed** 2019-11-28 11:12 UTC
Labels: bug, prio1

**Comment by yoursmanish** [comment] 2019-12-17 10:34
when can we expect this to available in [https://mvnrepository.com/artifact/io.fabric8/docker-maven-plugin](https://mvnrepository.com/artifact/io.fabric8/docker-maven-plugin)  
i am facing same issue with         
```
<groupId>io.fabric8</groupId>
<artifactId>docker-maven-plugin</artifactId>
<version>0.31.0</version>

```

**Comment by rohanKanojia** [comment] 2019-12-17 10:36
Hmm, I think most probably around Christmas. But Roland can answer it more precisely since he maintains it

**Comment by rhuss** [comment] 2019-12-17 10:57
I will try to make a release before the end of the week, or early next week.

Sorry for the delay, year end stress here :)

**Comment by yoursmanish** [comment] 2020-01-04 03:51
Hi @rhuss when do you think it can be released and will available in https://mvnrepository.com/?

**Comment by rhuss** [comment] 2020-01-08 18:49
Sorry, PTO was more vacation than expected ;-) But now that I'm back on track, I'm already preparing the release so should be out at latest at the end of this week.

**Comment by ziqianggeoffreychen** [comment] 2020-08-07 06:58
This issue is still observed occasionally in latest release **v0.33.0**
[INFO] --- docker-maven-plugin:0.33.0:push (push-when-install) @ my-project
[INFO] DOCKER> The push refers to repository [my repo]
[INFO] DOCKER> latest: digest: sha256: <some hash value>
[ERROR] DOCKER> Image <my_image>:latest could be pushed, but the temporary tag could not be removed

**Comment by nholtwerth** [comment] 2020-08-10 17:19
Hi, I am also focusing this error in v0.33.0.

**Comment by rhuss** [comment] 2020-08-30 15:10
Could you please post a sample project so that could be reproduced ?

**Comment by ziqianggeoffreychen** [comment] 2020-09-02 14:05
This issue is observed occasionally, or I can even say "rarely". The related projects are very common, nothing special.

**Comment by NancyChunlan** [comment] 2021-09-28 03:20
As checked, 0.32.0 has fixed this issue.
Logs as below:
```
05:18:39,969 [WARNING] DOCKER> Target image 'docker.registry/image' already exists. Tagging of 'image' will replace existing image

```

**Comment by NancyChunlan** [comment] 2021-09-28 03:22
> Could you please post a sample project so that could be reproduced ?

This issue happened when we have the image tagged with docker registry, and if we tried to tag a new image with the same tag (with docker registry) for docker:push, it will be failed.

**Comment by jntigura** [comment] 2021-11-03 18:32
Hi,
We're using docker-maven-plugin:0.37.0 and have intermittent occurrences of this bug with messages similar to this:
`[INFO] --- docker-maven-plugin:0.37.0:push (push-docker-image) @ *** ---`
`...`
`[ERROR] DOCKER> Unable to push '***' to registry '***' : tag does not exist: ***  [tag does not exist: *** ]`
