### ISSUE TITLE
Watch looks for shadow-files and doesn't remove old images

### ISSUE THREAD

**Issue by Khazrak** [fabric8io/docker-maven-plugin#365] opened 2016-01-25 10:01 UTC
When running:
mvn docker:start docker:watch -Ddocker.watchMode=both

[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.8:watch (default-cli) on project my-project: Execution default-cli of goal org.jolokia:docker-maven-plugin:0.13.8:watch failed: Destination /my/path/application.properties~ does not exist -> [Help 1]

I tested to add the shadow-file (application.properties~) and it complained of the next file. But if I added all the shadow-files then it would run.

But when it catches a rebuild of the java-artifact it fails to remove the old images:
[ERROR] DOCKER> conflict: unable to delete 1c8f5bd3776e (cannot be forced) - image is being used by running container fb2f6f76dc51 (Conflict: 409)
[ERROR] DOCKER> [docker-reg.iptv.got.telia.se:443/telia/drm-devices] "drm-devices": Error when rebuilding org.jolokia.docker.maven.access.DockerAccessException: Unable to remove image [1c8f5bd3776e]

When I check for the containers that uses them, they doesn't exist so I guess that it was the old containers that the plugin started.

**Comment by rhuss** [comment] 2016-04-01 08:21
Sorry for being late.

The latter error should be fixed in the newest version (0.14.2). The `cleanup` enum now supports a `try` which only prints a warning when the old container is still running. AFAIR does watch stop the container before building the new one, but it was some time since I tested this last. See also #401 

wrt to the backup file, it would be awesome if you would have an example project so that I could reproduce this.

**Comment by burtsevyg** [comment] 2017-05-11 16:19
[WARNING] DOCKER> [repo.local:5000/:0.1-SNAPSHOT] "app": Unable to remove image [sha256:b51fa] : conflict: unable to delete b51fa40164bb (cannot be forced) - image is being used by running container e7e95ee192ca (Conflict: 409) (old image) [conflict: unable to delete b51fa40164bb (cannot be forced) - image is being used by running container e7e95ee192ca (Conflict: 409)]

**Comment by rhuss** [comment] 2017-05-11 16:23
@burtsevyg could you please be a bit more specific ?

**Comment by burtsevyg** [comment] 2017-05-12 08:21
What information?

**Comment by rhuss** [comment] 2017-05-12 08:23
A sample project would be awesome since this behaviour does not occur for us. Also how you started the build. Everything which let us reproduce the issue is helpful.

**Comment by burtsevyg** [comment] 2017-05-12 18:26
I think that problem was in kernel "open file descriptor limit" in 1024 files for user running docker process. I cannot reproduce this anymore and I dont have root access to server but you can set this value as small as possible.
And I forget that server was restarted after change limit.
Thank you very much for your response.

**Comment by burtsevyg** [comment] 2018-11-07 08:03
Please, close this issue.

**Closed** 2018-11-07 12:36 UTC
