### ISSUE TITLE
Docker plugin should support Docker ARG commands and apply

### ISSUE THREAD

**Issue by dhoffer** [fabric8io/docker-maven-plugin#1402] opened 2020-11-09 20:59 UTC
I'm using your docker-maven-plugin to integrate generating and using a Dockerfile with our Maven build.

I need the Dockerfile to conform to certain requirements as it will be used by a 3rd party.

One of those requirements is that it supports the Docker ARG command.

The other requirement is that the FROM command will use those variables.

E.g. I need this to be supported:
ARG BASE_REGISTRY=localhost:5000
ARG BASE_TAG=1.11
ARG BASE_IMAGE=localhost:5000/redhat/openjdk/openjdk11
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

I'm using version 0.34.1 

I have branched your plugin to add support for ARG so that part is working but now I get this error.

[ERROR] DOCKER> Unable to check image [${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}] : {"message":"no such image: ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}: invalid reference format: repository name must be lowercase"} (Bad Request: 400) [{"message":"no such image: ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}: invalid reference format: repository name must be lowercase"} (Bad Request: 400)]

So this is failing in the hasImage() method because the variables are not being resolved.  Where in the docker-maven-plugin code would I apply the variables?  I'm not clear what code is calling this method.

Thanks.
-Dave

**Comment by rohanKanojia** [comment] 2020-11-19 09:27
@dhoffer : Hi, I think it's here:

https://github.com/fabric8io/docker-maven-plugin/blob/308792bf3342e68f5b4e92c9722de3a8588c1027/src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java#L85

Are you still working on this? If not, I can try looking into in whenever I find time.

**Comment by blackat** [comment] 2021-09-24 15:36
Hello,
I think there is already some activity around the issue [here](https://github.com/fabric8io/docker-maven-plugin/issues/1430)

**Comment by rohanKanojia** [comment] 2021-09-24 15:48
@blackat : Thanks for your comment, Do you think this issue is duplicate of #1430? If yes, let's close this one

**Comment by blackat** [comment] 2021-09-24 16:16
@rohanKanojia I think so, it is the same issue I have just got because the plugin seems not able yet to manage the ARG before the FROM, for this reason you get that error message.

**Comment by rohanKanojia** [comment] 2021-09-24 16:29
@blackat : Are you blocked due to this issue? Do you need a new release or can get going by building a SNAPSHOT version from master?

Thanks for verifying. I'll close this issue.

**Comment by rohanKanojia** [comment] 2021-09-24 16:29
Duplicate of #1430

**Closed** 2021-09-24 16:29 UTC

**Comment by blackat** [comment] 2021-09-25 11:15
> @blackat : Are you blocked due to this issue? Do you need a new release or can get going by building a SNAPSHOT version from master?
> 
> Thanks for verifying. I'll close this issue.

Hello,
currently I have followed the suggestion in the liked issue filtering the values and it works great, so I am not in a rush for the feature.

Thanks for having asked, appreciated.
