### ISSUE TITLE
Client version is too old

### ISSUE THREAD

**Issue by SirWayne** [fabric8io/docker-maven-plugin#1075] opened 2018-08-29 11:56 UTC
Try to build a docker image with Docker and Windows 10 (docker.host=tcp://127.0.0.1:2375), but I get follow error:

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.26.1:build (default) on x: Unable to check image [y] : client version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your cl
ient to a newer version (Bad Request: 400) -> [Help 1]
```

* d-m-p version : 0.26.1
* Maven version  : 3.5.0
* Docker Version: Docker version 18.06.0-ce
* Windows 10 with windows container

Does anybody know how i can upgrade the client version?

**Comment by rhuss** [comment] 2018-09-04 11:53
Duplicate of #1060. Let's continue over there ...

**Closed by rhuss** 2018-09-04 11:53 UTC
