### ISSUE TITLE
`DockerAccessException: Unable to pull` after update to version 0.14.2

### ISSUE THREAD

**Issue by heapifyman** [fabric8io/docker-maven-plugin#403] opened 2016-03-04 18:19 UTC
I just updated to version 0.14.2 from 0.13.7 and now my image cannot be pulled from my remote docker-host anymore:

```
[ERROR] v2 ping attempt failed with error: Get https://192.168.15.200:2376/v2/: x509: certificate signed by unknown authority
[ERROR] v1 ping attempt failed with error: Get https://192.168.15.200:2376/v1/_ping: x509: certificate signed by unknown authority (Internal Server Error: 500)
```

I am using the following global configuration settings:
```
<dockerHost>tcp://192.168.15.200:2376</dockerHost>
<certPath>${project.basedir}/docker-client-certs</certPath>
<registry>192.168.15.200:2376</registry>
```

and in the `<image><build>`:
```
<assembly>
    <dockerFileDir>${project.basedir}/src/main/docker</dockerFileDir>
    <descriptor>assembly.xml</descriptor>
</assembly>
```

The remote host is started with
```
DOCKER_OPTS="--tlsverify --tlscacert=/root/.docker/ca.pem --tlscert=/root/.docker/server-cert.pem --tlskey=/root/.docker/server-key.pem -H=unix:///var/run/docker.sock -H tcp://0.0.0.0:2376"
```
based on these [instructions](https://docs.docker.com/engine/security/https/)

**Comment by rhuss** [comment] 2016-03-04 18:49
Is your `ca.pem` included in `${project.basedir}/docker-client-certs` ?

**Comment by heapifyman** [comment] 2016-03-04 20:06
Yes, it is.

**Comment by rhuss** [comment] 2016-03-04 20:14
Could you please also check:

* Do you use clients certs ? I.e. do you have a `key.pem` and `cert.pem` in your cert directory ?
* Do you have a env variable `DOCKER_CERT_PATH` set ?
* If you switch back to 0.13.7 (only changing the version and group-id), does it work then ? (I ask because iirc there has been noc SSL related changes since this version).

Thanks ...

**Comment by heapifyman** [comment] 2016-03-04 20:31
> Do you use clients certs ? I.e. do you have a key.pem and cert.pem in your cert directory ?

Yes, both `key.pem` and `cert.pem` are there

> Do you have a env variable DOCKER_CERT_PATH set ?

No

> If you switch back to 0.13.7 (only changing the version and group-id), does it work then ?

Yes, with 0.13.7 it's working.
I only changed group-id and version and added `<registry>192.168.15.200:2376</registry>`, which wasn't needed before. But in 0.14.2 the plugin tries to pull from docker.io without it.

**Comment by rhuss** [comment] 2016-03-04 21:34
The issue is the registry part which is definitively wrong (and which result in the same error here). The registry is never the docker host itself (and has also another part).

Please try it without the registry. What error you receive when you dont put in the registry ?

**Comment by heapifyman** [comment] 2016-03-04 21:50
Without the `<registry>` I get `DockerAccessException: Error: image atb/tomcat6-java7-mysql-pureftp not found`.

The debug output shows `[INFO] DOCKER> ... Pulling repository docker.io/atb/tomcat6-java7-mysql-pureftp`

Which explains why it can't be found. Because it does not exist on docker.io, only on my remote docker host.

**Comment by rhuss** [comment] 2016-03-04 22:02
If you do a `docker image` on your host, do you then see `atb/tomcat6-java7-mysql-pureftp:latest` ? 
Probably not so you either need to build it, too or you need to pull it from a registry, which is **not** you Docker host but an external registry like dockerhub. If this is located on a private registry you need to specify this registry. 

In no case is the registry the same as the (remote) docker host.

**Comment by heapifyman** [comment] 2016-03-04 22:09
running `docker images` on the remote docker host (192.168.15.200) lists
`atb/tomcat6-java7-mysql-pureftp   0.0.3               7756d5c0a894`

Dockerfile uses `FROM atb/tomcat6-java7-mysql-pureftp:0.0.3'

It's never been anywhere else. And with 0.13.7 it is working. Why not with 0.14?

**Comment by heapifyman** [comment] 2016-03-08 15:12
I did some additional tests and found out that my build already fails with docker-maven-plugin version `0.13.8`.

I compared the debug output and here's the summary.
With version `0.13.7` the plugin seems to be doing roughly the following:

```
[DEBUG] http-outgoing-0 >> GET /v1.18/images/atb%2Fdocker-maven-test%3A0.0.3/json HTTP/1.1
...
[DEBUG] http-outgoing-0 << "No such image: atb/docker-maven-test:0.0.3[\n]"
[DEBUG] http-outgoing-0 << HTTP/1.1 404 Not Found
...
[INFO] Reading assembly descriptor: /docker-maven-test/src/main/docker/assembly.xml
...
[DEBUG] Adding artifact: de.atb:docker-maven-test:jar:0.0.3 with file: /docker-maven-test/target/docker-maven-test-0.0.3.jar to assembly location: docker-test.jar.
...
[INFO] Building tar: /docker-maven-test/target/docker/atb/docker-maven-test/0.0.3/tmp/docker-build.tar
...
[DEBUG] http-outgoing-1 >> POST /v1.18/build?t=atb%2Fdocker-maven-test%3A0.0.3&forcerm=1 HTTP/1.1
```
and then it goes on to build my target image `atb/docker-maven-test:0.0.3` based on my Dockerfile:
```
FROM atb/tomcat6-java7-mysql-pureftp:0.0.3
...
```


Starting with version `0.13.8` the log looks like this:
```
[DEBUG] http-outgoing-0 >> GET /v1.18/images/atb%2Ftomcat6-java7-mysql-pureftp%3A0.0.3/json HTTP/1.1
...
[DEBUG] http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
...
[DEBUG] http-outgoing-0 << "{"Id":"sha256:7756d5c0a894d78e3b85987ac9b61e509a3008d03913d0ca24156d95ccf016c1","RepoTags":["atb/tomcat6-java7-mysql-pureftp:0.0.3"], ....
....
[DEBUG] Executing request POST /v1.18/images/create?fromImage=atb%2Ftomcat6-java7-mysql-pureftp&tag=0.0.3 HTTP/1.1
...
[DEBUG] http-outgoing-1 >> POST /v1.18/images/create?fromImage=atb%2Ftomcat6-java7-mysql-pureftp&tag=0.0.3 HTTP/1.1
...
[DEBUG] http-outgoing-1 << HTTP/1.1 200 OK

[INFO] DOCKER> ... Pulling repository docker.io/atb/tomcat6-java7-mysql-pureftp
...
[DEBUG] http-outgoing-1 << "{"errorDetail":{"message":"Error: image atb/tomcat6-java7-mysql-pureftp not found"},"error":"Error: image atb/tomcat6-java7-mysql-pureftp not found"}[\r][\n]"
```

So it does find the base image (atb/tomcat6-java7-mysql-pureftp:0.0.3) on the remote host (`GET /v1.18/images/atb%2Ftomcat6-java7-mysql-pureftp%3A0.0.3/json` returns `200 OK`) but then somehow still tries to pull the image from `docker.io` which of course fails, since I never uploaded the base image to docker hub.


Based on the [changelog](https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/changelog.md) it does not look like I needed to change anything in my docker-maven-plugin configuration or my Dockerfile. But maybe I am missing something?

**Comment by rhuss** [comment] 2016-04-04 17:04
Could you check your `<autoPull>` configuration ? If is set to `always` then the base image will be pulled every time, regardless whether its is present or not.

The other change I see between 0.13.7 and 0.1.38 is that the option `noCache` was introduced for the build. How is your setting for this ?

Any change to get to a sample project so that I can reproduce it myself ?

**Comment by heapifyman** [comment] 2016-04-06 09:17
```<autoPull>``` was indeed set to ```always```. I changed it and now it's working again.

Looks like I misunderstood the description in the documentation. Sorry about that. 

I do not use ```<noCache>``` setting. I assume that this would build everything from scratch and disregard any previously build images or parts of images?

**Comment by rhuss** [comment] 2016-04-06 09:41
exactly, its the same as the `--no-cache` flag when running `docker build` on the command line.

If you don't mind I close this issue, feel free to reopen in case.

**Closed by rhuss** 2016-04-06 09:41 UTC
