### ISSUE TITLE
Support ECS task roles for ECR authentication

### ISSUE THREAD

**Issue by cybertiger** [fabric8io/docker-maven-plugin#1223] opened 2019-04-26 13:24 UTC
### Description

The recent addition of EC2 instance credentials support has broken using recent versions of the plugin on our Jenkins slaves.

Currently we use an ECS task role to grant access to the ECR repository, and use the `aws ecr get-login` command line to get docker credentials.

However the addition of EC2 instance role support #1177 ignores any credentials from docker login, and attempts to use the instance credentials which don't have access.

### Info

* d-m-p version : 0.29.0
* If it's a bug, how to reproduce :
On an EC2 instance, use aws ecr get-login to login to ECR using any non-instance credentials.
Attempt to push a docker image to ECR using the plugin.
* If it's a feature request, what is your use case :
Building with Jenkins slaves running in ECS using ECS task credentials for ECR access.

### Random

It's definitely a bug because it used to work.
It's also a feature request because the best way to fix (at least the instance of the bug that affects us) it is with a new feature.
Probably should not try to use either ECS task or instance credentials if there is a valid docker login for the repository either way.

### Reference

Retrieving ECS task AWS credentials is similar to retrieving instance credentials.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

ECS task credentials can be retrieved with:

curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI

**Comment by sebastiankirsch** [comment] 2019-11-06 16:20
Seems to be a duplicate of #1233

**Comment by rhuss** [comment] 2019-11-21 08:59
Agreed. Let it track over there at #1233.

**Closed by rhuss** 2019-11-21 08:59 UTC
