### ISSUE TITLE
Bug: Docker Multistage Build labeled stage is not detected

### ISSUE THREAD

**Issue by Xyaren** [fabric8io/docker-maven-plugin#1443] opened 2021-03-19 10:33 UTC
### Description
Mutlistage Docker Build is failing if named stage is used as a base later:

### Info

* docker-maven-plugin version: 0.34.1
* maven verison:  3.6.3

Example Dockerfile:
```
FROM centos AS first

RUN ls -la /

FROM centos as second

RUN ls -la /

# this fails
FROM second

RUN ls -la /
```

Error:
```
Failed to execute goal io.fabric8:docker-maven-plugin:0.34.1:build (build-docker) on project xxx-my-project-xxx Unable to pull 'second:latest' : {"message":"pull access denied for second, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"} (Not Found: 404)

```

**Comment by davoustp** [comment] 2021-06-07 15:21
Hi,
I agree with this report: the plugin fails because it attempts to pull any `FROM` image regardless of it being a named image (using `FROM ... AS <name>`) declared upstream in a multi-stage build.
This is actually a regression because it was previously working with version 0.28.0.

A simple project exhibiting the issue is attached to ease reproducing the issue: 
[maven-docker-plugin-fails-with-named-build-stages.tar.gz](https://github.com/fabric8io/docker-maven-plugin/files/6610117/maven-docker-plugin-fails-with-named-build-stages.tar.gz)

Trying to narrow the problem down shows that building with plugin version 0.28.0 passes with flying color when it fails quick & hard with plugin version 0.29.0.

Scanning through the 0.29.0 changelog hints that pull request #1057 is probably the culprit: instead of attempting the pull the first base image only, it attempts to do so with each and every base image (declared with `FROM`) without checking that the image may be a reference to an already declared and named build stage.

**Comment by rohanKanojia** [comment] 2021-06-07 15:24
@davoustp : Thanks for the investigation, Would it be possible to submit a fix for this issue?

**Comment by davoustp** [comment] 2021-06-07 15:25
Forking now and checking what can be done.

**Comment by rohanKanojia** [comment] 2021-06-07 15:31
@davoustp : Thanks a lot!

**Comment by davoustp** [comment] 2021-06-07 16:28
Done. Sonar analysis fails as it looks it required more permission than I have.

**Comment by rohanKanojia** [comment] 2021-06-07 16:35
Don't worry about it, our sonar job is failing right now due to removal of sonarcube token. I'll probably remove it or add new token

**Closed** 2021-06-08 17:40 UTC
Labels: bug
